"""

OOP = OBJECT ORIENTED PROGRAMMING 
ONE OF THE MOST IMPORTANT TOPICS IN CODING
OOP > FUNCTIONS > LOOPS
CLASS : BLUEPRINT FOR CREATING OBJECTS THAT DEFINES STRUCTURES AND ACTIONS OF THE OBJECTS.
OBJECT : ENTITY THAT HAS ITS OWN SET OF DATA AND CAN PERFORM ACTIONS DEFINED BY CLASS.

SYNTAX FOR CREATING CLASS:
    CLASS <CLASS_NAME>:
            KEY1 = VAL1 ...

SYNTAX FOR CREATING OBJECT:
    OBJ_NAME = CLASS_NAME()
    print(ONJ_NAME.KEY1)

"""
print("\n")

# Q. CREATE AND PRINT A CLASS AND OBJECT

class Student:                      # CREATING CLASS
    name = "KRISH LONGWANI"
    age = 20
s1 = Student()                      # CREATING OBJECT
print(s1.name)                      # PRINTING NAME

s2 = Student()                      # CREATING OBJECT
print (s2.age)                      # PRINTING AGE