"""
TUPLES :-
INBUILT DATA TYPE WHICH IS IMMUTABLE
STR, LIST, TUPLE ALL ARE ALMOST IDENTICAL
STR AND TUPLE ARE IMMUTABLE WHILE LIST IS MUTABLE 
WE CAN ACCESS ANY ELEMENT OF TUPLE BUT CANT CHANGE IT
INDEXING AND SLICING BOTH POSSIBLE IN TUPLE
WE CAN MAKE EMPTY TUPLE, SINGLE ELEMENT TUPLE, MULTI ELEMENT TUPLE WITH DIFFERENT SYNTAX
TUPLE METHODS : INDEX(), COUNT()
"""

# Q1. CREATE AN EMPTY TUPLE
tup1 = ()
print(tup1)
print(type(tup1))
print("\n")

# Q2. CREATE A SINGLE ELEMENT TUPLE
tup2 = (1,)     # IF WE DONT PUT ',' IN SINGLE ELEMENT TUPLE, IT WILL BE TAKEN AS INTEGER
print(tup2)
print(type(tup2))
print("\n")

# Q3. CREATE A MULTI ELEMENT TUPLE
tup3 = (1,2,3,4)    # IN MULTI ELEMENT TUPLE, COMMA IN END IS OPTIONAL
print(tup3)
print(type(tup3))
print("\n")

# Q4. USE INDEX() AND COUNT() METHODS IN A TUPLE
tup4 = (10,20,30,40,40)
print(tup4.index(20))       # RETURNS THE INDEX AT WHICH '20' IS 
print(tup4.count(40))       # RETURNS NUMBER OF TIMES '40' IS USED
print("\n")

# Q5. COUNT THE NUMBER OF STUDENTS WITH GRADE A
grade = ("A","B","C","D","A","B","C","D","A","A")
print(grade.count("A"))

# Q6. STORE THE ABOVE TUPLE IN A LIST AND PRINT THEM
grade1 = [grade]
grade1.sort()
print(grade1)
